<section class="people-ops-stack" data-recruitment-surface="interviews">
    <?php if($abilities['canScheduleInterview']): ?>
        <details id="recruitment-create" class="people-ops-panel" <?php if($errors->any()): ?> open <?php endif; ?>><summary class="people-ops-panel-head"><div><h2>Schedule interview</h2><p>Panel availability and company scope are revalidated by the server.</p></div><span class="people-button"><i class="fa-solid fa-plus" aria-hidden="true"></i> Interview</span></summary>
            <form method="POST" action="<?php echo e(route('recruitment.interviews.store')); ?>" class="people-form-grid people-ops-panel-body"><?php echo csrf_field(); ?>
                <label class="people-field">Candidate<select name="candidate_id" required><option value="">Select candidate</option><?php $__currentLoopData = $activeCandidateOptions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $candidate): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($candidate->id); ?>" <?php if((string)old('candidate_id') === (string)$candidate->id): echo 'selected'; endif; ?>><?php echo e($candidate->candidate_code); ?> · <?php echo e($candidate->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
                <label class="people-field">Round<input name="round_name" value="<?php echo e(old('round_name', 'Technical Round')); ?>" maxlength="120" required></label>
                <label class="people-field">Scheduled at<input type="datetime-local" name="scheduled_at" value="<?php echo e(old('scheduled_at')); ?>" required></label>
                <label class="people-field">Duration minutes<input type="number" name="duration_minutes" value="<?php echo e(old('duration_minutes', 60)); ?>" min="15" max="480" required></label>
                <label class="people-field">Mode<select name="mode" required><?php $__currentLoopData = $interviewModes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(old('mode', 'video') === $value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
                <label class="people-field">Venue or meeting link<input name="venue_or_link" value="<?php echo e(old('venue_or_link')); ?>" maxlength="500"></label>
                <label class="people-field is-wide">Panel members<select name="panel_user_ids[]" multiple required><?php $__currentLoopData = $panelUsers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $member): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($member->id); ?>" <?php if(in_array((string)$member->id, array_map('strval', old('panel_user_ids', [])), true)): echo 'selected'; endif; ?>><?php echo e($member->name); ?> · <?php echo e($member->email); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><small>Select one or more active internal users in the candidate company.</small></label>
                <div class="people-field is-wide"><button class="people-button is-primary" type="submit">Schedule interview</button></div>
            </form>
        </details>
    <?php endif; ?>

    <form method="GET" action="<?php echo e(route('recruitment.interviews.index')); ?>" class="people-ops-filterbar"><label class="people-field">Status<select name="status"><option value="">All statuses</option><?php $__currentLoopData = $interviewStatuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(($filters['status'] ?? '') === $value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><label class="people-field">Interview date<input type="date" name="date" value="<?php echo e($filters['date'] ?? ''); ?>"></label><button class="people-button" type="submit"><i class="fa-solid fa-filter" aria-hidden="true"></i> Apply</button><?php if(array_filter($filters)): ?><a class="people-button" href="<?php echo e(route('recruitment.interviews.index')); ?>">Clear</a><?php endif; ?></form>

    <article class="people-ops-panel has-mobile-cards"><header class="people-ops-panel-head"><div><h2>Interview schedule</h2><p>Only assigned panel members may submit feedback.</p></div><small><?php echo e($interviews->firstItem() ?? 0); ?>–<?php echo e($interviews->lastItem() ?? 0); ?> of <?php echo e($interviews->total()); ?></small></header>
        <div class="people-ops-table-wrap"><table class="people-ops-table"><caption>Scheduled recruitment interviews</caption><thead><tr><th scope="col">Interview</th><th scope="col">Candidate</th><th scope="col">Schedule</th><th scope="col">Panel</th><th scope="col">Status</th><th scope="col">Score</th><th scope="col">Feedback</th></tr></thead><tbody>
        <?php $__empty_1 = true; $__currentLoopData = $interviews; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $interview): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($interview->code); ?></strong><small><?php echo e($interview->round); ?> · <?php echo e($interview->mode); ?></small></td><td><?php echo e($interview->candidateName); ?><small><?php echo e($interview->candidateCode); ?> · <?php echo e($interview->openingTitle); ?></small></td><td><?php echo e($interview->scheduledDate); ?><small><?php echo e($interview->scheduledTime); ?> · <?php echo e($interview->duration); ?></small></td><td><?php echo e(implode(', ', $interview->panel) ?: 'No panel'); ?><small><?php echo e($interview->submittedFeedback); ?>/<?php echo e($interview->expectedFeedback); ?> feedback received</small></td><td><span class="people-status <?php echo e($interview->statusTone); ?>"><?php echo e($interview->statusLabel); ?></span></td><td><?php if($interview->score): ?><strong><?php echo e($interview->score); ?> / 100</strong><small><?php echo e($interview->scoreBand); ?> · <?php echo e($interview->scoreRule); ?></small><?php elseif($interview->averageRating): ?><strong><?php echo e($interview->averageRating); ?></strong><small>Panel average</small><?php else: ?><span class="people-status is-muted">Not calculated</span><?php endif; ?></td><td class="is-actions">
            <?php if($interview->canSubmitFeedback): ?><details><summary class="people-ops-action-link">Add feedback</summary><form method="POST" action="<?php echo e(route('recruitment.interviews.feedback', $interview->id)); ?>" class="people-ops-stack"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><label class="people-field">Rating<input type="number" name="rating" min="1" max="5" value="4" required></label><label class="people-field">Recommendation<select name="recommendation" required><option value="selected">Selected</option><option value="second_round">Second round</option><option value="hold">Hold</option><option value="rejected">Rejected</option></select></label><label class="people-field">Feedback<input name="feedback_note" maxlength="3000"></label><button class="people-button is-primary" type="submit">Submit</button></form></details><?php else: ?><span class="people-status is-muted">Unavailable</span><?php endif; ?>
        </td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7"><div class="people-ops-empty"><i class="fa-regular fa-calendar-check" aria-hidden="true"></i><strong>No interviews found</strong><span>Change the filters or schedule an authorized candidate interview.</span></div></td></tr><?php endif; ?>
        </tbody></table></div>
        <div class="people-ops-mobile-list">
            <?php $__empty_1 = true; $__currentLoopData = $interviews; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $interview): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                <article class="people-ops-mobile-card">
                    <header class="people-ops-mobile-card-head"><div><strong><?php echo e($interview->candidateName); ?></strong><small><?php echo e($interview->code); ?> · <?php echo e($interview->round); ?></small></div><span class="people-status <?php echo e($interview->statusTone); ?>"><?php echo e($interview->statusLabel); ?></span></header>
                    <dl class="people-ops-mobile-facts"><div><dt>Date</dt><dd><?php echo e($interview->scheduledDate); ?> <?php echo e($interview->scheduledTime); ?></dd></div><div><dt>Mode</dt><dd><?php echo e($interview->mode); ?></dd></div><div><dt>Panel</dt><dd><?php echo e(implode(', ', $interview->panel) ?: 'No panel'); ?></dd></div><div><dt>Feedback</dt><dd><?php echo e($interview->submittedFeedback); ?>/<?php echo e($interview->expectedFeedback); ?></dd></div></dl>
                    <?php if($interview->canSubmitFeedback): ?>
                        <div class="people-ops-mobile-actions"><details><summary class="people-button">Add feedback</summary><form method="POST" action="<?php echo e(route('recruitment.interviews.feedback', $interview->id)); ?>" class="people-ops-stack"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><label class="people-field">Rating<input type="number" name="rating" min="1" max="5" value="4" required></label><label class="people-field">Recommendation<select name="recommendation" required><option value="selected">Selected</option><option value="second_round">Second round</option><option value="hold">Hold</option><option value="rejected">Rejected</option></select></label><label class="people-field">Feedback<input name="feedback_note" maxlength="3000"></label><button class="people-button is-primary" type="submit">Submit feedback</button></form></details></div>
                    <?php endif; ?>
                </article>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                <div class="people-ops-empty"><strong>No interviews found</strong><span>Change the filters or schedule an authorized candidate interview.</span></div>
            <?php endif; ?>
        </div>
        <div class="people-pagination"><?php echo e($interviews->links()); ?></div>
    </article>
</section>
<?php /**PATH C:\Users\Mataji\Desktop\Codex1\Builder360\laravel-builder360\resources\views\recruitment\workspace\partials\interviews.blade.php ENDPATH**/ ?>