<?php if($abilities['canCreateCycle']): ?>
<details class="people-ops-panel" id="create-performance-cycle" <?php if($errors->any()): ?> open <?php endif; ?>>
    <summary class="people-ops-panel-head"><div><h2>Create performance cycle</h2><p>Configure a persisted review period using the existing scoring authority.</p></div></summary>
    <div class="people-ops-panel-body"><form method="POST" action="<?php echo e(route('hr.performance-cycles.store')); ?>" class="people-form-grid"><?php echo csrf_field(); ?>
        <label class="people-field"><span>Company</span><select class="people-control" name="company_id" required><?php $__currentLoopData = $companies; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $company): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($company->id); ?>" <?php if((string)old('company_id', auth()->user()->company_id)===(string)$company->id): echo 'selected'; endif; ?>><?php echo e($company->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
        <label class="people-field"><span>Cycle name</span><input class="people-control" name="name" maxlength="160" value="<?php echo e(old('name')); ?>" required></label>
        <label class="people-field"><span>Frequency</span><select class="people-control" name="frequency" required><?php $__currentLoopData = ['monthly'=>'Monthly','quarterly'=>'Quarterly','annual'=>'Annual']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(old('frequency')===$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
        <label class="people-field"><span>Status</span><select class="people-control" name="status" required><?php $__currentLoopData = ['draft'=>'Draft','active'=>'Active']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(old('status','draft')===$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
        <label class="people-field"><span>Starts on</span><input class="people-control" type="date" name="starts_on" value="<?php echo e(old('starts_on')); ?>" required></label>
        <label class="people-field"><span>Ends on</span><input class="people-control" type="date" name="ends_on" value="<?php echo e(old('ends_on')); ?>" required></label>
        <label class="people-field"><span>Review due</span><input class="people-control" type="date" name="review_due_on" value="<?php echo e(old('review_due_on')); ?>"></label>
        <label class="people-field"><span>Department</span><select class="people-control" name="department"><option value="">All departments</option><?php $__currentLoopData = $departments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $department): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($department); ?>" <?php if(old('department')===$department): echo 'selected'; endif; ?>><?php echo e($department); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
        <label class="people-field"><span>Project</span><select class="people-control" name="project_id"><option value="">All projects</option><?php $__currentLoopData = $projects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $project): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($project->id); ?>" <?php if((string)old('project_id')===(string)$project->id): echo 'selected'; endif; ?>><?php echo e($project->code); ?> - <?php echo e($project->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
        <label class="people-field"><span>Rating minimum</span><input class="people-control" type="number" name="rating_scale_min" min="1" max="9" step="1" value="<?php echo e(old('rating_scale_min',1)); ?>" required></label>
        <label class="people-field"><span>Rating maximum</span><input class="people-control" type="number" name="rating_scale_max" min="2" max="10" step="1" value="<?php echo e(old('rating_scale_max',5)); ?>" required></label>
        <label class="people-field"><span>Passing score</span><input class="people-control" type="number" name="passing_score" min="1" max="10" step="0.01" value="<?php echo e(old('passing_score',3)); ?>" required></label>
        <button class="people-button is-primary" type="submit">Create cycle</button>
    </form></div>
</details>
<?php endif; ?>

<section class="people-ops-panel has-mobile-cards" aria-labelledby="performance-cycles-title">
    <header class="people-ops-panel-head"><div><h2 id="performance-cycles-title">Performance cycles</h2><p><?php echo e($cycles->total()); ?> authorized cycle<?php echo e($cycles->total() === 1 ? '' : 's'); ?>.</p></div></header>
    <div class="people-ops-panel-body"><form method="GET" action="<?php echo e(route('hr.performance-cycles.index')); ?>" class="people-ops-filterbar"><label class="people-field"><span>Status</span><select class="people-control" name="status"><option value="">All statuses</option><?php $__currentLoopData = ['draft'=>'Draft','active'=>'Active','closed'=>'Closed','archived'=>'Archived']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(request('status')===$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><label class="people-field"><span>Frequency</span><select class="people-control" name="frequency"><option value="">All frequencies</option><?php $__currentLoopData = ['monthly'=>'Monthly','quarterly'=>'Quarterly','annual'=>'Annual']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(request('frequency')===$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><label class="people-field"><span>Department</span><select class="people-control" name="department"><option value="">All departments</option><?php $__currentLoopData = $departments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $department): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($department); ?>" <?php if(request('department')===$department): echo 'selected'; endif; ?>><?php echo e($department); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><button class="people-button is-primary">Apply filters</button><a class="people-button" href="<?php echo e(route('hr.performance-cycles.index')); ?>">Clear</a></form></div>
    <div class="people-ops-table-wrap"><table class="people-ops-table"><caption>Performance cycles</caption><thead><tr><th scope="col">Cycle</th><th scope="col">Period</th><th scope="col">Population</th><th scope="col">Scale</th><th scope="col">Status</th><th scope="col" class="is-number">Reviews</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $cycles; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $cycle): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($cycle->code); ?></strong><small><?php echo e($cycle->name); ?> / <?php echo e(ucfirst($cycle->frequency)); ?></small></td><td><?php echo e($cycle->period); ?><small>Due <?php echo e($cycle->reviewDue); ?></small></td><td><?php echo e($cycle->department); ?><small><?php echo e($cycle->project); ?></small></td><td><?php echo e($cycle->scale); ?><small>Pass <?php echo e($cycle->passingScore); ?></small></td><td><span class="people-status is-<?php echo e($cycle->status === 'active' ? 'success' : ($cycle->status === 'draft' ? 'warning' : 'muted')); ?>"><?php echo e($cycle->statusLabel); ?></span></td><td class="is-number"><?php echo e($cycle->reviewCount); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6"><div class="people-ops-empty"><strong>No performance cycles found</strong><span>Clear the filters or create an authorized cycle.</span></div></td></tr><?php endif; ?></tbody></table></div>
    <div class="people-ops-mobile-list"><?php $__empty_1 = true; $__currentLoopData = $cycles; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $cycle): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><article class="people-ops-mobile-card"><header class="people-ops-mobile-card-head"><div><strong><?php echo e($cycle->name); ?></strong><small><?php echo e($cycle->code); ?></small></div><span class="people-status is-info"><?php echo e($cycle->statusLabel); ?></span></header><dl class="people-ops-mobile-facts"><div><dt>Period</dt><dd><?php echo e($cycle->period); ?></dd></div><div><dt>Department</dt><dd><?php echo e($cycle->department); ?></dd></div><div><dt>Scale</dt><dd><?php echo e($cycle->scale); ?></dd></div><div><dt>Reviews</dt><dd><?php echo e($cycle->reviewCount); ?></dd></div></dl></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="people-ops-empty"><strong>No performance cycles found</strong></div><?php endif; ?></div>
    <?php echo e($cycles->withQueryString()->links()); ?>

</section>
<?php /**PATH C:\Users\Mataji\Desktop\Codex1\Builder360\laravel-builder360\resources\views\hr\performance\partials\cycles.blade.php ENDPATH**/ ?>