<?php $__env->startSection('title', 'Employee Movements - Builder360 ERP-CRM'); ?>
<?php $__env->startSection('content'); ?>
<?php if (isset($component)) { $__componentOriginal7b46c749cdd3ead475dfb1495ff30ad9 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal7b46c749cdd3ead475dfb1495ff30ad9 = $attributes; } ?>
<?php $component = App\View\Components\Hr\PeopleWorkspace::resolve(['title' => 'Employee Movements','description' => $employee->employee_code.' - '.$employee->name.' - '.$employee->designation,'eyebrow' => 'People / Employee 360','active' => 'employees'] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('hr.people-workspace'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\App\View\Components\Hr\PeopleWorkspace::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
     <?php $__env->slot('actions', null, []); ?> <a class="people-button" href="<?php echo e(route('hr.employees.index')); ?>"><i class="fa-solid fa-arrow-left" aria-hidden="true"></i> Employee directory</a> <?php $__env->endSlot(); ?>
    <?php if(session('status')): ?><section class="blade-alert blade-alert-success" role="status"><?php echo e(session('status')); ?></section><?php endif; ?>
    <?php if($errors->any()): ?><section class="blade-alert blade-alert-danger" role="alert" tabindex="-1"><strong>Please correct the highlighted movement fields.</strong><ul><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ul></section><?php endif; ?>
    <?php if (isset($component)) { $__componentOriginald7d6991c6f8cbf6e7a6895c044edeaa1 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginald7d6991c6f8cbf6e7a6895c044edeaa1 = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.hr.employee-profile-navigation','data' => ['links' => $profileNavigation,'active' => 'movements']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('hr.employee-profile-navigation'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['links' => \Illuminate\View\Compilers\BladeCompiler::sanitizeComponentAttribute($profileNavigation),'active' => 'movements']); ?>
<?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginald7d6991c6f8cbf6e7a6895c044edeaa1)): ?>
<?php $attributes = $__attributesOriginald7d6991c6f8cbf6e7a6895c044edeaa1; ?>
<?php unset($__attributesOriginald7d6991c6f8cbf6e7a6895c044edeaa1); ?>
<?php endif; ?>
<?php if (isset($__componentOriginald7d6991c6f8cbf6e7a6895c044edeaa1)): ?>
<?php $component = $__componentOriginald7d6991c6f8cbf6e7a6895c044edeaa1; ?>
<?php unset($__componentOriginald7d6991c6f8cbf6e7a6895c044edeaa1); ?>
<?php endif; ?>
    <?php if($abilities['canCreate']): ?>
    <section class="blade-card" x-data="{ movementType: '<?php echo e(old('movement_type','transfer')); ?>' }"><div class="blade-card-header"><div><p class="blade-eyebrow">Effective-dated change</p><h2>Create employee movement</h2></div></div>
        <form method="POST" action="<?php echo e(route('hr.employees.movements.store',$employee)); ?>" class="blade-form-grid"><?php echo csrf_field(); ?>
            <label>Movement type<select name="movement_type" x-model="movementType" required><?php $__currentLoopData = ['transfer'=>'Transfer','promotion'=>'Promotion','department_change'=>'Department change','reporting_change'=>'Reporting change','salary_change'=>'Salary change','status_change'=>'Status change','grade_change'=>'Grade change']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>"><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><label>Effective on<input type="date" name="effective_on" value="<?php echo e(old('effective_on',now()->toDateString())); ?>" required></label><input type="hidden" name="status" value="pending">
            <label x-show="movementType === 'transfer'">Branch<select name="new_values[branch_id]" :disabled="movementType !== 'transfer'"><option value="">No branch</option><?php $__currentLoopData = $branches; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $branch): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($branch->id); ?>"><?php echo e($branch->code); ?> &middot; <?php echo e($branch->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label x-show="movementType === 'transfer'">Project<select name="new_values[project_id]" :disabled="movementType !== 'transfer'"><option value="">All projects</option><?php $__currentLoopData = $projects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $project): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($project->id); ?>"><?php echo e($project->code); ?> &middot; <?php echo e($project->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label x-show="movementType === 'transfer' || movementType === 'department_change'">Department<input name="new_values[department]" :disabled="!['transfer','department_change'].includes(movementType)" value="<?php echo e(old('new_values.department',$employee->department)); ?>"></label>
            <label x-show="movementType === 'promotion'">Designation<input name="new_values[designation]" :disabled="movementType !== 'promotion'" value="<?php echo e(old('new_values.designation',$employee->designation)); ?>"></label>
            <label x-show="movementType === 'promotion' || movementType === 'grade_change'">Grade<input name="new_values[grade]" :disabled="!['promotion','grade_change'].includes(movementType)" value="<?php echo e(old('new_values.grade',$employee->grade)); ?>"></label>
            <label x-show="movementType === 'promotion' || movementType === 'salary_change'">Monthly CTC<input type="number" min="0" step="0.01" name="new_values[monthly_ctc]" :disabled="!['promotion','salary_change'].includes(movementType)" value="<?php echo e(old('new_values.monthly_ctc',$employee->monthly_ctc)); ?>"></label>
            <label x-show="movementType === 'reporting_change'">Reporting manager<select name="new_values[manager_employee_id]" :disabled="movementType !== 'reporting_change'"><option value="">No reporting manager</option><?php $__currentLoopData = $managers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $manager): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($manager->id); ?>"><?php echo e($manager->employee_code); ?> &middot; <?php echo e($manager->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label x-show="movementType === 'status_change'">Employment status<select name="new_values[status]" :disabled="movementType !== 'status_change'"><?php $__currentLoopData = ['active'=>'Active','inactive'=>'Inactive','on_notice'=>'On notice','separated'=>'Separated']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>"><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label class="blade-form-wide">Reason<textarea name="reason" maxlength="2000" required><?php echo e(old('reason')); ?></textarea></label><label class="blade-form-wide">Remarks<textarea name="remarks" maxlength="2000"><?php echo e(old('remarks')); ?></textarea></label><button class="blade-primary-action">Submit movement</button>
        </form>
    </section>
    <?php endif; ?>
    <section class="blade-card"><div class="blade-card-header"><div><p class="blade-eyebrow">Movement register</p><h2>Effective-dated history</h2></div></div><form method="GET" action="<?php echo e(route('hr.employees.movements.index',$employee)); ?>" class="blade-filter-grid"><label>Type<select name="movement_type"><option value="">All types</option><?php $__currentLoopData = ['transfer','promotion','department_change','reporting_change','salary_change','status_change','grade_change']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(request('movement_type')===$value): echo 'selected'; endif; ?>><?php echo e(str_replace('_',' ',ucfirst($value))); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><label>Status<select name="status"><option value="">All statuses</option><?php $__currentLoopData = ['pending','approved','cancelled']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(request('status')===$value): echo 'selected'; endif; ?>><?php echo e(ucfirst($value)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><button class="blade-secondary-action">Apply filters</button></form>
        <div class="blade-table-wrap"><table class="blade-table"><caption class="sr-only">Effective-dated movement history for <?php echo e($employee->name); ?></caption><thead><tr><th scope="col">Movement</th><th scope="col">Type</th><th scope="col">Effective date</th><th scope="col">Changes</th><th scope="col">Created by</th><th scope="col">Status</th><th scope="col">Action</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $movements; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $movement): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?> <?php ($actions=$movementActions[$movement->id]??[]); ?><tr><td><strong><?php echo e($movement->number); ?></strong><br><span><?php echo e($movement->reason); ?></span></td><td><?php echo e($movement->typeLabel); ?></td><td><?php echo e($movement->effectiveDate); ?></td><td><?php $__currentLoopData = $movement->changes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $change): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><span><?php echo e($change->label); ?>: <?php echo e($change->value); ?></span><br><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?> <?php if($movement->hasRestrictedCompensation): ?><span>Compensation details: Restricted</span><?php elseif($movement->changes === []): ?><span>No field changes recorded</span><?php endif; ?></td><td><?php echo e($movement->createdByName); ?></td><td><span class="blade-status-pill"><?php echo e($movement->statusLabel); ?></span></td><td><?php if($actions['canApprove']??false): ?><form method="POST" action="<?php echo e(route('hr.employees.movements.approve',[$employee,$movement->id])); ?>" class="blade-inline-form"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><label class="sr-only" for="movement-remarks-<?php echo e($movement->id); ?>">Approval remarks for <?php echo e($movement->number); ?></label><input id="movement-remarks-<?php echo e($movement->id); ?>" name="remarks" maxlength="2000" placeholder="Approval remarks"><button class="blade-primary-action" aria-label="Approve and apply movement <?php echo e($movement->number); ?>">Approve and apply</button></form><?php else: ?><span>No action available</span><?php endif; ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7">No employee movements are available for the selected filters.</td></tr><?php endif; ?></tbody></table></div><?php echo e($movements->withQueryString()->links()); ?></section>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal7b46c749cdd3ead475dfb1495ff30ad9)): ?>
<?php $attributes = $__attributesOriginal7b46c749cdd3ead475dfb1495ff30ad9; ?>
<?php unset($__attributesOriginal7b46c749cdd3ead475dfb1495ff30ad9); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal7b46c749cdd3ead475dfb1495ff30ad9)): ?>
<?php $component = $__componentOriginal7b46c749cdd3ead475dfb1495ff30ad9; ?>
<?php unset($__componentOriginal7b46c749cdd3ead475dfb1495ff30ad9); ?>
<?php endif; ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.builder360-classic', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\Mataji\Desktop\Codex1\Builder360\laravel-builder360\resources\views/hr/employees/movements.blade.php ENDPATH**/ ?>