<section class="people-ops-panel has-mobile-cards" aria-labelledby="department-performance-title">
    <header class="people-ops-panel-head">
        <div><h2 id="department-performance-title">Department performance dashboard</h2><p>Factual review completion and final scores from the complete authorized query.</p></div>
    </header>
    <div class="people-ops-panel-body">
        <form method="GET" action="<?php echo e(route('hr.performance-dashboard.index')); ?>" class="people-ops-filterbar">
            <label class="people-field"><span>Cycle</span><select class="people-control" name="cycle_id"><option value="">All visible cycles</option><?php $__currentLoopData = $activeCycles; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $cycle): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($cycle->id); ?>" <?php if((string)request('cycle_id') === (string)$cycle->id): echo 'selected'; endif; ?>><?php echo e($cycle->cycle_code); ?> - <?php echo e($cycle->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label class="people-field"><span>Department</span><select class="people-control" name="department"><option value="">All departments</option><?php $__currentLoopData = $departments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $department): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($department); ?>" <?php if(request('department') === $department): echo 'selected'; endif; ?>><?php echo e($department); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <button class="people-button is-primary" type="submit">Apply filters</button>
            <a class="people-button" href="<?php echo e(route('hr.performance-dashboard.index')); ?>">Clear</a>
        </form>
    </div>
    <div class="people-ops-table-wrap">
        <table class="people-ops-table"><caption>Department performance outcomes</caption>
            <thead><tr><th scope="col">Department</th><th scope="col" class="is-number">Employees</th><th scope="col" class="is-number">Reviews</th><th scope="col">Completion</th><th scope="col" class="is-number">Open</th><th scope="col" class="is-number">Average score</th><th scope="col" class="is-number">PIP</th></tr></thead>
            <tbody><?php $__empty_1 = true; $__currentLoopData = $departmentRows; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($row->department); ?></strong></td><td class="is-number"><?php echo e($row->employees); ?></td><td class="is-number"><?php echo e($row->reviews); ?></td><td><div class="people-ops-progress"><progress value="<?php echo e($row->completionRate); ?>" max="100"><?php echo e($row->completionRate); ?>%</progress><span><?php echo e($row->completionRate); ?>%</span></div><small><?php echo e($row->closedReviews); ?> closed</small></td><td class="is-number"><?php echo e($row->openReviews); ?></td><td class="is-number"><?php echo e($row->averageFinalScore ?? '—'); ?></td><td class="is-number"><?php echo e($row->pipRequired); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7"><div class="people-ops-empty"><i class="fa-solid fa-chart-column" aria-hidden="true"></i><strong>No department review outcomes</strong><span>No persisted performance reviews match the selected authorized scope.</span></div></td></tr><?php endif; ?></tbody>
        </table>
    </div>
    <div class="people-ops-mobile-list">
        <?php $__empty_1 = true; $__currentLoopData = $departmentRows; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><article class="people-ops-mobile-card"><header class="people-ops-mobile-card-head"><strong><?php echo e($row->department); ?></strong><span class="people-status is-info"><?php echo e($row->completionRate); ?>% closed</span></header><dl class="people-ops-mobile-facts"><div><dt>Employees</dt><dd><?php echo e($row->employees); ?></dd></div><div><dt>Reviews</dt><dd><?php echo e($row->reviews); ?></dd></div><div><dt>Average final score</dt><dd><?php echo e($row->averageFinalScore ?? '—'); ?></dd></div><div><dt>PIP required</dt><dd><?php echo e($row->pipRequired); ?></dd></div></dl></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="people-ops-empty"><strong>No department review outcomes</strong><span>No persisted performance reviews match the selected scope.</span></div><?php endif; ?>
    </div>
</section>
<?php /**PATH C:\Users\Mataji\Desktop\Codex1\Builder360\laravel-builder360\resources\views\hr\performance\partials\dashboard.blade.php ENDPATH**/ ?>