<?php $__env->startSection('title', 'My Receipts - Builder360 ERP-CRM'); ?>
<?php $__env->startSection('content'); ?>
<div class="blade-workspace" aria-labelledby="buyer-receipts-title">
<header class="blade-workspace-header"><div><p class="blade-dashboard-eyebrow">Buyer Portal</p><h1 id="buyer-receipts-title">My Receipts</h1><p>Approved payment receipts linked to your bookings.</p></div><?php echo $__env->make('buyer.partials.navigation', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></header>
<section class="blade-dashboard-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Receipts</span><h2>Approved receipts</h2></div><small><?php echo e($records->total()); ?> record(s)</small></div><div class="blade-dashboard-table-wrap"><table class="blade-dashboard-table"><thead><tr><th>Receipt</th><th>Booking</th><th>Project</th><th>Date</th><th>Mode</th><th>Amount</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $records; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $receipt): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($receipt->receipt_number); ?></strong></td><td><?php echo e($receipt->booking?->booking_code ?? '—'); ?></td><td><?php echo e($receipt->project?->name ?? '—'); ?></td><td><?php echo e($receipt->receipt_date?->format('d M Y') ?? '—'); ?></td><td><?php echo e(strtoupper($receipt->payment_mode)); ?></td><td>₹<?php echo e(number_format((float) $receipt->amount, 2)); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6">No approved receipts are available.</td></tr><?php endif; ?>
</tbody></table></div><div class="blade-pagination"><?php echo e($records->links()); ?></div></section></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.builder360-classic', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\Mataji\Desktop\Codex1\Builder360\laravel-builder360\resources\views\buyer\receipts.blade.php ENDPATH**/ ?>