<?php $__env->startSection('title', 'My Payments - Builder360 ERP-CRM'); ?>
<?php $__env->startSection('content'); ?>
<div class="blade-workspace" aria-labelledby="buyer-payments-title">
<header class="blade-workspace-header"><div><p class="blade-dashboard-eyebrow">Buyer Portal</p><h1 id="buyer-payments-title">My Payments</h1><p>Payment requests and their current completion status.</p></div><?php echo $__env->make('buyer.partials.navigation', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></header>
<?php if(session('status')): ?><div class="blade-alert blade-alert-success"><?php echo e(session('status')); ?></div><?php endif; ?>
<?php if($errors->any()): ?><div class="blade-alert blade-alert-danger"><strong>Check the payment details.</strong><ul><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ul></div><?php endif; ?>
<section class="blade-dashboard-card"><form method="GET" action="<?php echo e(route('buyer.payment-requests.index')); ?>" class="blade-filter-grid blade-filter-grid-compact"><label>Status<select name="status"><option value="">All statuses</option><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(($filters['status']??'')===$value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><button class="blade-secondary-action">Apply filter</button><a class="blade-secondary-action" href="<?php echo e(route('buyer.payment-requests.index')); ?>">Reset</a></form></section>
<section class="blade-dashboard-card"><div class="blade-dashboard-section-title"><div><span class="blade-dashboard-label">Payments</span><h2>Payment request register</h2></div><small><?php echo e($records->total()); ?> record(s)</small></div><div class="blade-dashboard-table-wrap"><table class="blade-dashboard-table"><thead><tr><th>Request</th><th>Booking</th><th>Purpose</th><th>Amount</th><th>Expires</th><th>Status</th><th>Action</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $records; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $payment): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($payment->request_number); ?></strong></td><td><?php echo e($payment->booking?->booking_code ?? '—'); ?></td><td><?php echo e($payment->purpose); ?></td><td>₹<?php echo e(number_format((float)$payment->amount,2)); ?></td><td><?php echo e($payment->expires_at?->format('d M Y') ?? '—'); ?></td><td><span class="blade-status-pill"><?php echo e($statuses[$payment->status] ?? ucfirst($payment->status)); ?></span></td><td><?php if($payment->status==='requested'): ?><details class="blade-row-actions"><summary>Pay</summary><form method="POST" action="<?php echo e(route('buyer.payment-requests.pay',$payment)); ?>" class="blade-inline-form"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><select name="payment_mode" required><option value="upi">UPI</option><option value="card">Card</option><option value="netbanking">Net Banking</option><option value="wallet">Wallet</option></select><input name="instrument_number" placeholder="Transaction reference" required maxlength="120"><button class="blade-primary-action" type="submit">Complete payment</button></form></details><?php else: ?><span class="blade-muted">No action</span><?php endif; ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7">No payment requests are available.</td></tr><?php endif; ?>
</tbody></table></div><div class="blade-pagination"><?php echo e($records->links()); ?></div></section></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.builder360-classic', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\Mataji\Desktop\Codex1\Builder360\laravel-builder360\resources\views\buyer\payment-requests.blade.php ENDPATH**/ ?>