<?php ($sourceEntries = $abilities['canManage'] ? $availableEntries : $availableEntries->filter(fn($entry) => (int) $entry->employee?->user_id === (int) auth()->id())); ?>

<?php if($abilities['canRequestSwap']): ?>
    <section class="people-ops-panel people-roster-create">
        <header class="people-ops-panel-head"><div><h2>Request shift swap</h2><p>Only published, unlocked working entries are eligible. Approval exchanges both employees atomically.</p></div><span class="people-status is-warning">Approval required</span></header>
        <form class="people-ops-panel-body people-form-grid" method="POST" action="<?php echo e(route('hr.attendance-shift-swaps.store')); ?>" data-disable-on-submit>
            <?php echo csrf_field(); ?>
            <label class="people-field">Your/source entry<select class="people-control" name="source_roster_entry_id" required><option value="">Select source entry</option><?php $__currentLoopData = $sourceEntries; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $entry): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($entry->id); ?>:<?php echo e($entry->lock_version); ?>"><?php echo e($entry->work_date->format('d M Y')); ?> · <?php echo e($entry->employee->name); ?> · <?php echo e($entry->shift?->code); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label class="people-field">Target entry<select class="people-control" name="target_roster_entry_id" required><option value="">Select target entry</option><?php $__currentLoopData = $availableEntries; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $entry): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($entry->id); ?>:<?php echo e($entry->lock_version); ?>"><?php echo e($entry->work_date->format('d M Y')); ?> · <?php echo e($entry->employee->name); ?> · <?php echo e($entry->shift?->code); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
            <label class="people-field is-wide">Reason<textarea class="people-control people-textarea" name="reason" required maxlength="2000" placeholder="Explain why this swap is needed."><?php echo e(old('reason')); ?></textarea></label>
            <div class="people-form-actions is-wide"><button class="people-button is-primary" type="submit"><i class="fa-solid fa-right-left" aria-hidden="true"></i> Submit swap request</button></div>
        </form>
    </section>
<?php endif; ?>

<section class="people-ops-panel has-mobile-cards">
    <header class="people-ops-panel-head"><div><h2>Shift swap requests</h2><p>Maker-checker decisions preserve both roster entries and their audit trace.</p></div><span class="people-count"><?php echo e($swaps->total()); ?> requests</span></header>
    <div class="people-ops-table-wrap"><table class="people-ops-table"><caption>Attendance shift swap requests</caption><thead><tr><th scope="col">Request</th><th scope="col">Source</th><th scope="col">Target</th><th scope="col">Reason</th><th scope="col">Status</th><th scope="col">Actions</th></tr></thead><tbody>
    <?php $__empty_1 = true; $__currentLoopData = $swaps; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $swap): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
        <tr>
            <td><strong><?php echo e($swap->request_number); ?></strong><small><?php echo e($swap->created_at->format('d M Y, H:i')); ?> · <?php echo e($swap->requestedBy?->name); ?></small></td>
            <td><strong><?php echo e($swap->sourceEntry?->employee?->name); ?></strong><small><?php echo e($swap->sourceEntry?->work_date?->format('d M Y')); ?> · <?php echo e($swap->sourceEntry?->shift?->code); ?></small></td>
            <td><strong><?php echo e($swap->targetEntry?->employee?->name); ?></strong><small><?php echo e($swap->targetEntry?->work_date?->format('d M Y')); ?> · <?php echo e($swap->targetEntry?->shift?->code); ?></small></td>
            <td><?php echo e(str($swap->reason)->limit(70)); ?></td>
            <td><span class="<?php echo \Illuminate\Support\Arr::toCssClasses(['people-status', 'is-warning' => $swap->status === 'submitted', 'is-success' => $swap->status === 'approved', 'is-danger' => in_array($swap->status, ['rejected', 'cancelled'], true)]); ?>"><?php echo e(str($swap->status)->headline()); ?></span><?php if($swap->decision_note): ?><small><?php echo e($swap->decision_note); ?></small><?php endif; ?></td>
            <td class="is-actions"><div class="people-roster-actions">
                <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('approve', $swap)): ?><form method="POST" action="<?php echo e(route('hr.attendance-shift-swaps.approve', $swap)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><input type="hidden" name="lock_version" value="<?php echo e($swap->lock_version); ?>"><button class="people-button is-primary" type="submit">Approve</button></form><?php endif; ?>
                <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('reject', $swap)): ?><form class="people-inline-form" method="POST" action="<?php echo e(route('hr.attendance-shift-swaps.reject', $swap)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><input type="hidden" name="lock_version" value="<?php echo e($swap->lock_version); ?>"><input class="people-control" name="decision_note" placeholder="Required rejection reason" required maxlength="2000"><button class="people-button is-danger" type="submit">Reject</button></form><?php endif; ?>
                <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('cancel', $swap)): ?><form method="POST" action="<?php echo e(route('hr.attendance-shift-swaps.cancel', $swap)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><input type="hidden" name="lock_version" value="<?php echo e($swap->lock_version); ?>"><button class="people-button" type="submit">Cancel</button></form><?php endif; ?>
            </div></td>
        </tr>
    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
        <tr><td colspan="6"><div class="people-ops-empty"><i class="fa-solid fa-right-left" aria-hidden="true"></i><strong>No shift swap requests</strong><span>Eligible employees can request a swap from published roster entries.</span></div></td></tr>
    <?php endif; ?>
    </tbody></table></div>
    <div class="people-ops-mobile-list"><?php $__currentLoopData = $swaps; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $swap): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><article class="people-ops-mobile-card"><header class="people-ops-mobile-card-head"><div><strong><?php echo e($swap->request_number); ?></strong><small><?php echo e($swap->created_at->format('d M Y')); ?></small></div><span class="people-status is-warning"><?php echo e(str($swap->status)->headline()); ?></span></header><dl class="people-ops-mobile-facts"><div><dt>Source</dt><dd><?php echo e($swap->sourceEntry?->employee?->name); ?> · <?php echo e($swap->sourceEntry?->shift?->code); ?></dd></div><div><dt>Target</dt><dd><?php echo e($swap->targetEntry?->employee?->name); ?> · <?php echo e($swap->targetEntry?->shift?->code); ?></dd></div><div><dt>Reason</dt><dd><?php echo e($swap->reason); ?></dd></div></dl></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
    <div class="people-pagination"><span>Showing <?php echo e($swaps->firstItem() ?? 0); ?> to <?php echo e($swaps->lastItem() ?? 0); ?> of <?php echo e($swaps->total()); ?></span><?php echo e($swaps->links()); ?></div>
</section>
<?php /**PATH C:\Users\Mataji\Desktop\Codex1\Builder360\laravel-builder360\resources\views\hr\attendance\rosters\swaps.blade.php ENDPATH**/ ?>