<section class="people-ops-stack" data-recruitment-surface="offers">
    <?php if($abilities['canCreateOffer']): ?>
        <details id="recruitment-create" class="people-ops-panel" <?php if($errors->any()): ?> open <?php endif; ?>><summary class="people-ops-panel-head"><div><h2>Create offer draft</h2><p>Offer creation and release remain separated by policy.</p></div><span class="people-button"><i class="fa-solid fa-plus" aria-hidden="true"></i> Offer</span></summary>
            <form method="POST" action="<?php echo e(route('recruitment.offers.store')); ?>" class="people-form-grid people-ops-panel-body"><?php echo csrf_field(); ?>
                <label class="people-field">Candidate<select name="candidate_id" required><option value="">Select candidate</option><?php $__currentLoopData = $offerCandidateOptions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $candidate): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($candidate->id); ?>" <?php if((string)old('candidate_id') === (string)$candidate->id): echo 'selected'; endif; ?>><?php echo e($candidate->candidate_code); ?> · <?php echo e($candidate->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label>
                <label class="people-field">Template code<input name="template_code" value="<?php echo e(old('template_code', 'APPOINTMENT_STANDARD')); ?>" maxlength="80" required></label>
                <label class="people-field">Offered CTC<input type="number" name="offered_ctc" value="<?php echo e(old('offered_ctc')); ?>" min="1" step="0.01" required></label>
                <label class="people-field">Joining date<input type="date" name="joining_date" value="<?php echo e(old('joining_date')); ?>" min="<?php echo e(now()->addDay()->toDateString()); ?>" required></label>
                <label class="people-field">Candidate name placeholder<input name="placeholders[candidate_name]" value="<?php echo e(old('placeholders.candidate_name')); ?>" maxlength="255" required></label>
                <label class="people-field">Designation placeholder<input name="placeholders[designation]" value="<?php echo e(old('placeholders.designation')); ?>" maxlength="255" required></label>
                <label class="people-field">Department placeholder<input name="placeholders[department]" value="<?php echo e(old('placeholders.department')); ?>" maxlength="255" required></label>
                <label class="people-field">Joining date placeholder<input type="date" name="placeholders[joining_date]" value="<?php echo e(old('placeholders.joining_date')); ?>" required></label>
                <label class="people-field">Offered CTC placeholder<input type="number" name="placeholders[offered_ctc]" value="<?php echo e(old('placeholders.offered_ctc')); ?>" min="1" step="0.01" required></label>
                <div class="people-field is-wide"><button class="people-button is-primary" type="submit">Create offer draft</button></div>
            </form>
        </details>
    <?php endif; ?>

    <form method="GET" action="<?php echo e(route('recruitment.offers.index')); ?>" class="people-ops-filterbar"><label class="people-field">Status<select name="status"><option value="">All statuses</option><?php $__currentLoopData = $offerStatuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $value => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($value); ?>" <?php if(($filters['status'] ?? '') === $value): echo 'selected'; endif; ?>><?php echo e($label); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></label><button class="people-button" type="submit"><i class="fa-solid fa-filter" aria-hidden="true"></i> Apply</button><?php if(array_filter($filters)): ?><a class="people-button" href="<?php echo e(route('recruitment.offers.index')); ?>">Clear</a><?php endif; ?></form>

    <article class="people-ops-panel has-mobile-cards"><header class="people-ops-panel-head"><div><h2>Offer lifecycle</h2><p>Drafts can be released only by an independent authorized reviewer.</p></div><small><?php echo e($offers->firstItem() ?? 0); ?>–<?php echo e($offers->lastItem() ?? 0); ?> of <?php echo e($offers->total()); ?></small></header>
        <div class="people-ops-table-wrap"><table class="people-ops-table"><caption>Recruitment offers</caption><thead><tr><th scope="col">Offer</th><th scope="col">Candidate</th><th scope="col">Template</th><th scope="col">CTC / Joining</th><th scope="col">Status</th><th scope="col">Owner</th><th scope="col">Actions</th></tr></thead><tbody>
        <?php $__empty_1 = true; $__currentLoopData = $offers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $offer): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($offer->number); ?></strong><small><?php echo e($offer->openingTitle); ?> · <?php echo e($offer->department); ?></small></td><td><?php echo e($offer->candidateName); ?><small><?php echo e($offer->candidateCode); ?></small></td><td><?php echo e($offer->template); ?></td><td><?php echo e($offer->offeredCtc ?? 'Restricted'); ?><small><?php echo e($offer->joiningDate); ?></small></td><td><span class="people-status <?php echo e($offer->statusTone); ?>"><?php echo e($offer->statusLabel); ?></span></td><td><?php echo e($offer->createdBy); ?><small><?php echo e($offer->releasedBy); ?> · <?php echo e($offer->releasedAt); ?></small></td><td class="is-actions"><?php if($offer->canRelease): ?><form method="POST" action="<?php echo e(route('recruitment.offers.release', $offer->id)); ?>" class="people-ops-list-actions"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><input name="release_note" maxlength="2000" placeholder="Release note"><button class="people-button is-primary" type="submit">Release</button></form><?php else: ?><span class="people-status is-muted"><?php echo e($offer->status === 'draft' ? 'Release unavailable' : 'No action'); ?></span><?php endif; ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7"><div class="people-ops-empty"><i class="fa-solid fa-file-signature" aria-hidden="true"></i><strong>No offers found</strong><span>Change the filters or create an authorized offer draft.</span></div></td></tr><?php endif; ?>
        </tbody></table></div>
        <div class="people-ops-mobile-list">
            <?php $__empty_1 = true; $__currentLoopData = $offers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $offer): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                <article class="people-ops-mobile-card">
                    <header class="people-ops-mobile-card-head"><div><strong><?php echo e($offer->candidateName); ?></strong><small><?php echo e($offer->number); ?> · <?php echo e($offer->candidateCode); ?></small></div><span class="people-status <?php echo e($offer->statusTone); ?>"><?php echo e($offer->statusLabel); ?></span></header>
                    <dl class="people-ops-mobile-facts"><div><dt>Opening</dt><dd><?php echo e($offer->openingTitle); ?></dd></div><div><dt>Joining</dt><dd><?php echo e($offer->joiningDate); ?></dd></div><div><dt>Template</dt><dd><?php echo e($offer->template); ?></dd></div><div><dt>Created by</dt><dd><?php echo e($offer->createdBy); ?></dd></div></dl>
                    <?php if($offer->canRelease): ?>
                        <div class="people-ops-mobile-actions"><form method="POST" action="<?php echo e(route('recruitment.offers.release', $offer->id)); ?>" class="people-ops-list-actions"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><label class="people-field"><span class="sr-only">Release note for <?php echo e($offer->number); ?></span><input name="release_note" maxlength="2000" placeholder="Release note"></label><button class="people-button is-primary" type="submit">Release offer</button></form></div>
                    <?php elseif($offer->status === 'draft'): ?>
                        <p class="people-subtext">Release unavailable for your role.</p>
                    <?php endif; ?>
                </article>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                <div class="people-ops-empty"><strong>No offers found</strong><span>Change the filters or create an authorized offer draft.</span></div>
            <?php endif; ?>
        </div>
        <div class="people-pagination"><?php echo e($offers->links()); ?></div>
    </article>
</section>
<?php /**PATH C:\Users\Mataji\Desktop\Codex1\Builder360\laravel-builder360\resources\views\recruitment\workspace\partials\offers.blade.php ENDPATH**/ ?>